### PR TITLE
Bump `indent-string`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
To match the version used by `listr-update-renderer`.

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
Linting is failing because of an unrelated issue.

**Comment by SamVerschueren** [comment]
Sorry for the late reply. I totally missed this one. After looking at the code, I noticed `indent-string` is not used anymore. It's probably a leftover from the days when the renderers were still part of the core package. I'm going to remove it from the dependencies list.

**Comment by SamVerschueren** [comment]
Apparently we had some unused dependencies https://github.com/SamVerschueren/listr/commit/f5d0b0d8df9f338a059a12b09147c036b4b6fca9. Removed them and released a new version. Sorry for the delay on this one.

**Comment by wtgtybhertgeghgtwtg** [comment]
I can't believe I missed that.  Thank you for resolving this.

**Pull request closed without merging**
