### PR TITLE
Use ow for argument validation

### LINKED ISSUE #100: Use ow for argument validation?
[sindresorhus/ow](https://github.com/sindresorhus/ow) could be used for argument validation which is done in a few places like [`lib/task.js`](https://github.com/SamVerschueren/listr/blob/588036807405e6b4b961ea7b13f88b25978bbe96/lib/task.js#L16-L34). Would you accept a PR for the change?

### PR DESCRIPTION
**Pull request by sudo-suhas**
Closes #100

### CODE REVIEW

**Comment by sudo-suhas** [comment]
_Copied from https://github.com/SamVerschueren/listr/issues/100#issuecomment-388687858_

Should I try to use `ow` for this section - [SamVerschueren/listr:index.js@`5880368`#L18-L29](https://github.com/SamVerschueren/listr/blob/588036807405e6b4b961ea7b13f88b25978bbe96/index.js#L18-L29)? Right now the error messages are quite helpful because they are quite specific for each invalid input scenario. I could use the following but that would end up with rather generic error messages:
```js
ow(tasks, ow.any(
			ow.undefined.label('tasks'),
			ow.array.label('tasks'),
			ow.object.label('tasks').is(
				x => typeof x.title !== 'string' && typeof x.task !== 'function'
			)
		));
```

<details>
<summary>Error output for comparison:</summary>

```
  test › create

  /home/suhaskaranth/dev/oss/listr/test/test.js:6

   5:   t.notThrows(() => new Listr());                                
   6:   t.throws(() => new Listr('foo'), 'Expected an array of tasks');
   7:                                                                  

  Threw unexpected exception:

  ArgumentError (Error) {
    message: `Any predicate failed with the following errors:␊
    - Expected `tasks` to be of type `undefined` but received type `string`␊
    - Expected `tasks` to be of type `array` but received type `string`␊
    - Expected `tasks` to be of type `object` but received type `string``,
  }



  test › throw error if a task object is provided

  /home/suhaskaranth/dev/oss/listr/test/test.js:36

   35: test('throw error if a task object is provided', t => {                                                                           
   36:   t.throws(() => new Listr({title: 'foo', task: () => {}}), 'Expected an array of tasks or an options object, got a task object');
   37: });                                                                                                                               

  Threw unexpected exception:

  ArgumentError (Error) {
    message: `Any predicate failed with the following errors:␊
    - Expected `tasks` to be of type `undefined` but received type `Object`␊
    - Expected `tasks` to be of type `array` but received type `Object`␊
    - Expected object `tasks` `[object Object]` to pass custom validation function`,
  }

```

</details>

**Comment by sindresorhus** [comment]
@sudo-suhas You can just leave it like it is for now.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sudo-suhas** [comment]
Will do, please give me some time. I am away from my system for a couple of days.

**Comment by sudo-suhas** [comment]
Done.

**Pull request closed without merging**
