### PR TITLE
Move to ESM

### PR DESCRIPTION
**Pull request by LitoMore**
### Changes

- Move to ESM
- Use [c8](https://github.com/bcoe/c8) instead of `nyc`.
- Add Codecov actions
- Target Node.js `^12.20.0 || ^14.13.1 || >=16.0.0`
- License and package.json fields cleanup (`github.com/SamVerschueren` -> `https://github.com/SamVerschueren`)
- Update dependencies to latest

I will rewrite our project with TypeScript in next PR or commit. Type declarations coming soon.

### CODE REVIEW

**Comment by LitoMore** [comment]
@SamVerschueren How about move those renderer packages into this project?

That will be more convenient for updating type definitions in the same project.

We could deprecate those packages or move them to here to make it to a mono repo.

**Comment by SamVerschueren** [comment]
Moving the renderers in here makes sense! Would definitely be a good idea instead of keeping them separately.

**Comment by LitoMore** [comment]
@SamVerschueren Shall we merge this PR? Or just continue the TypeScript refactor work in this PR?

**Comment by SamVerschueren** [comment]
Merged. Think it makes sense to do it separately.

**Comment by SamVerschueren** [comment]
Thanks for working on this 🙏

**Pull request merged**
